window.siteData = {
  updates: [
    {
      date: "2026-05-15",
      title: "University of Rochester graduation",
      body:
        "Graduated cum laude from the University of Rochester with a double major in Business Information Systems and Data Science and a minor in Computer Science.",
    },
    {
      date: "2026-04",
      title: "Data Science capstone",
      body:
        "Completed the Paychex product recommendation agent with Shixin Lin, Zhengyang Zhu, and Lexiang Yang.",
    },
    {
      date: "2024-10-01",
      title: "Green finance working paper",
      body:
        "Completed the working paper \"Research on the Impact of Green Finance Reforms on Pilot-Listed Companies in China\" with Haiyang Zeng, Yiqi Jin, Che Jiang, Huijun Zeng, and Yuxiang Cheng.",
    },
    {
      date: "2022-08-22",
      title: "University of Rochester",
      body: "Started undergraduate studies at the University of Rochester.",
    },
    {
      date: "2022-07",
      title: "High school graduation",
      body: "Graduated from Beijing Haidian International School.",
    },
  ],
  photographySections: [
    {
      id: "series-01",
      label: "Series 01",
      title: "Series 01",
      folder: "assets/photos/series-01/",
      photos: [],
      minimumSlots: 3,
    },
    {
      id: "series-02",
      label: "Series 02",
      title: "Series 02",
      folder: "assets/photos/series-02/",
      photos: [],
      minimumSlots: 3,
    },
    {
      id: "archive",
      label: "Archive",
      title: "Archive",
      folder: "assets/photos/archive/",
      photos: [],
      minimumSlots: 3,
    },
  ],
  travel: {
    countries: [
      {
        iso3: "CHN",
        name: "China",
        cities: [
          "Hebei Province",
          "Shanxi Province",
          "Liaoning Province",
          "Jiangsu Province",
          "Zhejiang Province",
          "Anhui Province",
          "Fujian Province",
          "Shandong Province",
          "Henan Province",
          "Hubei Province",
          "Hunan Province",
          "Guangdong Province",
          "Hainan Province",
          "Sichuan Province",
          "Guizhou Province",
          "Yunnan Province",
          "Shaanxi Province",
          "Inner Mongolia Autonomous Region",
          "Tibet Autonomous Region",
          "Beijing",
          "Tianjin",
          "Shanghai",
          "Chongqing",
        ],
      },
      {
        iso3: "TWN",
        name: "Taiwan Province",
        cities: ["Taiwan Province"],
      },
      {
        iso3: "HKG",
        name: "Hong Kong SAR",
        cities: ["Hong Kong"],
      },
      {
        iso3: "MAC",
        name: "Macao SAR",
        cities: ["Macao"],
      },
      {
        iso3: "FRA",
        name: "France",
        cities: ["Paris"],
      },
      {
        iso3: "ITA",
        name: "Italy",
        cities: ["Milan", "Florence", "Rome"],
      },
      {
        iso3: "CHE",
        name: "Switzerland",
        cities: ["Zurich"],
      },
      {
        iso3: "GBR",
        name: "United Kingdom",
        cities: ["Eastbourne", "London", "Manchester", "York", "Nottingham", "Brighton", "Portsmouth"],
      },
      {
        iso3: "SGP",
        name: "Singapore",
        cities: ["Singapore"],
      },
      {
        iso3: "THA",
        name: "Thailand",
        cities: ["Thailand"],
      },
      {
        iso3: "IDN",
        name: "Indonesia",
        cities: ["Indonesia"],
      },
      {
        iso3: "AUS",
        name: "Australia",
        cities: ["Melbourne", "Gold Coast", "Sydney"],
      },
      {
        iso3: "JPN",
        name: "Japan",
        cities: ["Japan"],
      },
      {
        iso3: "KOR",
        name: "South Korea",
        cities: ["South Korea"],
      },
      {
        iso3: "USA",
        name: "United States",
        cities: [
          "Rochester",
          "New York",
          "Boston",
          "Atlanta",
          "Denver",
          "Vail",
          "Los Angeles",
          "San Francisco",
          "Seattle",
          "Phoenix",
          "Las Vegas",
          "Sedona",
          "Hawaii",
          "Orlando",
        ],
      },
      {
        iso3: "MNP",
        name: "Northern Mariana Islands",
        cities: ["Saipan"],
      },
      {
        iso3: "BHS",
        name: "The Bahamas",
        cities: ["Nassau"],
      },
      {
        iso3: "QAT",
        name: "Qatar",
        cities: ["Qatar"],
      },
    ],
  },
};
